**Ejercicio 1: Carga y Manipulación de Datos**

•	Contexto: Antes de aplicar cualquier transformación o análisis, debemos cargar de manera correcta nuestro dataset garantizando que el delimitador y la codificación operen sin errores, y generar métricas calculadas básicas.  

•	Instrucción: Importa pandas as pd. Lee el archivo ventas_bogota_limpiar.csv usando el separador correcto (sep=";") y la codificación "utf-8". Crea una nueva columna llamada "venta_total" multiplicando la columna "precio" por la columna "cantidad". Imprime las primeras 3 filas de las columnas "id_venta", "producto" y "venta_total".

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('ventas_bogota_limpiar.csv', sep = ';', encoding = 'utf-8')
df

,id_venta,fecha,producto,categoria,precio,cantidad,ciudad,metodo_pago,cliente_satisfecho
0,1,13/02/2024,Monitor,Accesorios,1140503.31,6,Barranquilla,Tarjeta,si
1,2,29/02/2024,Audífonos,Accesorios,2786223.89,2,Barranquilla,NaN,si
2,3,5/04/2024,Teclado,Accesorios,958850.40,3,Cali,NaN,No
3,4,12/05/2024,Audífonos,Periféricos,1544815.40,5,Barranquilla,Efectivo,NaN
4,5,13/05/2024,Audífonos,Periféricos,NaN,9,bogotá,tarjeta,Sí
...,...,...,...,...,...,...,...,...,...
200,11,14/04/2024,Monitor,Periféricos,618930.71,8,bogotá,NaN,NO
201,12,26/02/2024,Teclado,Periféricos,560183.09,1,Bogotá,Tarjeta,si
202,13,29/04/2024,Audífonos,Periféricos,887096.50,6,Medellín,Efectivo,Sí
203,14,23/05/2024,Mouse,Accesorios,1929054.93,1,Cali,tarjeta,si
204,15,4/01/2024,Monitor,Periféricos,2505366.79,2,NaN,Tarjeta,NaN

In [4]:
df['venta_total'] = df['precio'] * df['cantidad']

In [5]:
df[['id_venta', 'producto', 'venta_total']].head(3)

   id_venta   producto  venta_total
0         1    Monitor   6843019.86
1         2  Audífonos   5572447.78
2         3    Teclado   2876551.20

**Ejercicio 2: Manipulación de Cadenas (.str)**

•	Contexto: Los datos de texto suelen presentar irregularidades tipográficas o diferencias de mayúsculas y minúsculas que afectan el análisis posterior.  

•	Instrucción: Utiliza el descriptor .str para convertir los valores de la columna "ciudad" a minúsculas y eliminar posibles espacios sobrantes, guardando el resultado en una nueva columna llamada "ciudad_limpia". Asimismo, estandariza la columna "categoria" reemplazando la palabra "Periféricos" por "Perifericos". Muestra las primeras 3 filas de estas columnas.

In [14]:
df['ciudad_limpia'] = df['ciudad'].str.lower()
ciudad_limpia

0      barranquilla
1      barranquilla
2              cali
3      barranquilla
4            bogotá
           ...
200          bogotá
201          bogotá
202        medellín
203            cali
204             NaN
Name: ciudad, Length: 205, dtype: str

In [18]:
df['categoria_nueva'] = df['categoria'].replace({'Periféricos': 'Perifericos'})
categoria_nueva

0       Accesorios
1       Accesorios
2       Accesorios
3      Perifericos
4      Perifericos
          ...
200    Perifericos
201    Perifericos
202    Perifericos
203     Accesorios
204    Perifericos
Name: categoria, Length: 205, dtype: str

In [17]:
df[['categoria_nueva', 'ciudad_limpia']].head()

  categoria_nueva ciudad_limpia
0      Accesorios  barranquilla
1      Accesorios  barranquilla
2      Accesorios          cali
3     Perifericos  barranquilla
4     Perifericos        bogotá

**Ejercicio 3: Ordenamiento de Datos (sort_values)**

•	Contexto: Para identificar rápidamente las transacciones con mayor impacto financiero dentro del dataset, requerimos estructurar los registros de manera descendente.  

•	Instrucción: Ordena el DataFrame principal en función de la columna "venta_total" de mayor a menor (ascending=False). Muestra las 3 transacciones principales indicando su ID, producto y valor total de venta.

In [21]:
df[['id_venta', 'producto', 'venta_total']].sort_values('venta_total', ascending = False).head(3)

     id_venta   producto  venta_total
171       172     Laptop  30537174.06
162       163  Audífonos  30346474.95
59         60      Mouse  30282741.99

**Ejercicio 4: Agrupamiento y Agregaciones (groupby)**

•	Contexto: El negocio requiere un reporte consolidado que resuma el rendimiento económico por categorías de productos.  

•	Instrucción: Agrupa el DataFrame por la columna de tu preferencia y usa el método sum sobre la columna ‘Ventas_total’ para obtener solo el valor de las agrupaciones.  

•	En otra agrupación aplica la misma fórmula pero devuelve la agrupación pro promedio de la columna ‘Ventas_total’

In [31]:
df.groupby('producto')['venta_total'].sum()

producto
Audífonos    3.183823e+08
Laptop       3.956426e+08
Monitor      3.252636e+08
Mouse        2.513606e+08
Teclado      3.538768e+08
Name: venta_total, dtype: float64

In [32]:
df.groupby('producto')['venta_total'].mean()

producto
Audífonos    9.647948e+06
Laptop       9.649820e+06
Monitor      6.776325e+06
Mouse        7.855018e+06
Teclado      9.829911e+06
Name: venta_total, dtype: float64